import { Role } from "./enum";

export const TeacherFormInitialData = {
  // Personal Information
  firstname: "",
  lastname: "",
  email: "",
  DOB: "",
  gender: "",
  nationality: "",
  phone: "",
  street: "",
  city: "",
  state: "",
  zipcode: "",
  country: "",

  employeeId: "",
  hireDate: "",
  qualification: "",
  experience: "",
  previousInstitution: "",
  salary: 0,
  employmentType: "",
  subjectSpecialization: "",

  degree: "",
  university: "",
  graduationYear: 0,
  classesAssigned: [],
  preferredGrades: "",

  achievements: "",
  notes: "",
  photo: null,
  role: Role.TEACHER,
};

export const StudentFormIntialData = {
  firstname: "",
  lastname: "",
  email: "",
  dateOfBirth: "",
  gender: "",
  nationality: "",
  religion: "",
  bloodGroup: "",
  phone: "",
  street: "",
  city: "",
  state: "",
  zipcode: "",
  country: "",
  classId: "",
  admissionDate: "",
  previousSchool: "",
  grade: "",
  parentId: "",
  parentfirstname: "",
  parentlastname: "",
  parentemail: "",
  parentphone: "",
  relationship: "",
  conditions: "",
  allergies: "",
  medications: "",
  doctorName: "",
  doctorPhone: "",
  photo: null as File | null,
};

export const ClassFormInitialData = {
  name: "",
  grade: "",
  capacity: "",
  roomNumber: "",
  description: "",
  teacherId: "",
  academicYear: "",
  schedule: {
    startDate: "",
    endDate: "",
    startTime: "",
    endTime: "",
    days: [] as string[],
  },
  subjects: [] as string[],
};

export const ExamFormInitialData = {
  title: "",
  teacherId: "",
  subjectId: "",
  classId: "",
  date: "",
  startTime: "",
  duration: "",
  examType: "",
};
