export const TeacherFormInitialData = {
  // Personal Information
  firstName: "",
  lastName: "",
  email: "",
  dateOfBirth: "",
  gender: "",
  nationality: "",
  phone: "",
  emergencyContactName: "",
  emergencyContactPhone: "",
  address: "",
  city: "",
  state: "",
  zipCode: "",
  country: "",
  employeeId: "",
  joinDate: "",
  subjectSpecialization: "",
  qualification: "",
  experience: "",
  previousInstitution: "",
  salary: "",
  employmentType: "",
  degree: "",
  university: "",
  graduationYear: "",
  additionalCertifications: "",
  classesAssigned: [],
  maxClassesPerWeek: "",
  preferredGrades: "",
  skills: "",
  achievements: "",
  notes: "",
  photo: null,
};

export const StudentFormIntialData = {
  firstName: "",
  lastName: "",
  email: "",
  dateOfBirth: "",
  gender: "",
  nationality: "",
  religion: "",
  bloodGroup: "",
  phone: "",
  address: "",
  city: "",
  state: "",
  zipCode: "",
  country: "",
  classId: "",
  admissionDate: "",
  previousSchool: "",
  grade: "",
  parentId: "",
  parentname: "",
  parentemail: "",
  parentphone: "",
  relationship: "",
  medicalConditions: "",
  allergies: "",
  medications: "",
  doctorName: "",
  doctorPhone: "",
  photo: null as File | null,
};

export const ClassFormInitialData = {
  name: "",
  grade: "",
  // section: "",
  capacity: "",
  roomNumber: "",
  description: "",
  teacherId: "",
  academicYear: "",
  schedule: {
    startDate: "",
    endDate: "",
    startTime: "",
    endTime: "",
    days: [] as string[],
  },
  subjects: [] as string[],
};
